export { default as Home } from './Home.vue'
export { default as Exit } from './Exit.vue'
export { default as Person } from './Person.vue'
export { default as Triangle } from './Triangle.vue'
export { default as Star } from './Star.vue'
export { default as Fork } from './Fork.vue'
export { default as Close } from './Close.vue'
export { default as Arrow } from './Arrow.vue'
